 File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 63, in wrapped_app
    await response(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 150, in __call__
    await send(
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in _send
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 473, in send
    self.access_logger.info(
Message: '%s - "%s %s HTTP/%s" %d'
Arguments: ('172.18.0.5:39234', 'GET', '/history?limit=5', '1.0', 401)
2025-05-18 05:51:12 - uvicorn.error - INFO - Shutting down
2025-05-18 05:51:12 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-18 05:51:12 - uvicorn.error - INFO - Application shutdown complete.
2025-05-18 05:51:12 - uvicorn.error - INFO - Finished server process [1]
2025-05-18 05:53:24 - app.main - INFO - Database tables already exist, skipping table creation...
2025-05-18 05:53:24 - uvicorn.error - INFO - Started server process [1]
2025-05-18 05:53:24 - uvicorn.error - INFO - Waiting for application startup.
2025-05-18 05:53:24 - app.main - INFO - Starting ProbeOps API
2025-05-18 05:53:24 - app.main - INFO - Database initialization completed: {'tiers_initialized': False, 'users_initialized': {'admin_created': True, 'standard_user_created': True}, 'subscriptions_assigned': False}
2025-05-18 05:53:24 - app.main - INFO - Rate limiting background tasks started
2025-05-18 05:53:24 - app.main - INFO - ProbeOps API started successfully
2025-05-18 05:53:24 - uvicorn.error - INFO - Application startup complete.
2025-05-18 05:53:24 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

